name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and Push Docker Image
        run: |
          # Replace 'myapp:v1' with your desired image name and tag
          docker build -t myapp:v1 .

          # Replace 'myapp:v1' and 'docker.io/library/hotelprofessionals:latest' with your desired image name and tag
          docker tag myapp:v1 docker.io/library/hotelprofessionals:latest

          # Push the image to Docker Hub
          docker push docker.io/library/hotelprofessionals:latest

      # Add the following steps to deploy to Knative

      - name: Deploy to Knative
        run: |
          kubectl apply -f knative-revision.yaml
        env:
          KUBECONFIG: ${{ secrets.KUBE_CONFIG }}
